/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'app', 'purchase-invoice', 'page.tsx');
const raw = fs.readFileSync(filePath, 'utf8');
const crlf = raw.includes('\r\n');
const content = crlf ? raw.replace(/\r\n/g, '\n') : raw;
let lines = content.split('\n');

// ── 0. Add ArrowRight to imports if missing ──
if (!lines.some(l => l.trim() === 'ArrowRight,')) {
  const idx = lines.findIndex(l => l.includes('ArrowUpDown,'));
  if (idx !== -1) { lines.splice(idx, 0, '  ArrowRight,'); console.log('Added ArrowRight import'); }
}

// ── 1. Find CreateInvoiceModal boundaries dynamically ──
const startIdx = lines.findIndex(l => l.startsWith('function CreateInvoiceModal('));
if (startIdx === -1) { console.error('ERROR: CreateInvoiceModal not found'); process.exit(1); }

let depth = 0, endIdx = startIdx;
for (let i = startIdx; i < lines.length; i++) {
  for (const ch of lines[i]) { if (ch === '{') depth++; else if (ch === '}') depth--; }
  if (depth === 0) { endIdx = i; break; }
}
console.log(`Replacing lines [${startIdx}..${endIdx}] (${endIdx - startIdx + 1} lines)`);

// ── 2. New UploadDrawer function ──
const uploadDrawer = [
"function UploadDrawer({ onClose }: Readonly<{ onClose: () => void }>) {",
"  const shouldReduceMotion = useReducedMotion();",
"  const easeOut = [0.22, 1, 0.36, 1] as const;",
"  const springEase = [0.16, 1, 0.3, 1] as const;",
"",
"  const [phase, setPhase] = useState<\"upload\" | \"processing\">(\"upload\");",
"  const [isDragOver, setIsDragOver] = useState(false);",
"  const [files, setFiles] = useState<File[]>([]);",
"  const [statuses, setStatuses] = useState<number[]>([]);",
"  const fileInputRef = useRef<HTMLInputElement>(null);",
"  const cameraInputRef = useRef<HTMLInputElement>(null);",
"  const timerRef = useRef<ReturnType<typeof setTimeout>[]>([]);",
"",
"  const hasFiles = files.length > 0;",
"  const doneCount = statuses.filter(s => s === 3).length;",
"  const allDone = statuses.length > 0 && doneCount === statuses.length;",
"  const progressPct = statuses.length === 0 ? \"0%\" : `${Math.round((doneCount / statuses.length) * 100)}%`;",
"",
"  useEffect(() => { return () => { timerRef.current.forEach(clearTimeout); }; }, []);",
"",
"  function addFiles(incoming: FileList | null) {",
"    if (!incoming) return;",
"    setFiles((prev) => [...prev, ...Array.from(incoming)]);",
"  }",
"  function removeFile(index: number) {",
"    setFiles((prev) => prev.filter((_, i) => i !== index));",
"  }",
"  function handleDragOver(e: React.DragEvent) { e.preventDefault(); setIsDragOver(true); }",
"  function handleDragLeave(e: React.DragEvent) { e.preventDefault(); setIsDragOver(false); }",
"  function handleDrop(e: React.DragEvent) { e.preventDefault(); setIsDragOver(false); addFiles(e.dataTransfer.files); }",
"",
"  function handleUpload() {",
"    timerRef.current.forEach(clearTimeout);",
"    timerRef.current = [];",
"    setStatuses(new Array(files.length).fill(0));",
"    setPhase(\"processing\");",
"    const stagger    = shouldReduceMotion ? 15 : Math.min(300, Math.floor(2500 / Math.max(files.length, 1)));",
"    const readDur    = shouldReduceMotion ? 40 : 1200;",
"    const analyzeDur = shouldReduceMotion ? 40 : 1400;",
"    files.forEach((_, i) => {",
"      const base = i * stagger;",
"      timerRef.current.push(setTimeout(() => setStatuses(p => { const n = [...p]; n[i] = 1; return n; }), base));",
"      timerRef.current.push(setTimeout(() => setStatuses(p => { const n = [...p]; n[i] = 2; return n; }), base + readDur));",
"      timerRef.current.push(setTimeout(() => setStatuses(p => { const n = [...p]; n[i] = 3; return n; }), base + readDur + analyzeDur));",
"    });",
"  }",
"",
"  return (",
"    <div className=\"fixed inset-0 z-40 flex justify-end overflow-hidden\">",
"      <motion.div",
"        className=\"absolute inset-0 bg-black/20 backdrop-blur-[2px]\"",
"        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}",
"        transition={{ duration: shouldReduceMotion ? 0.14 : 0.24, ease: springEase }}",
"        onClick={phase === \"upload\" ? onClose : undefined}",
"      />",
"      <motion.div",
"        className=\"relative z-10 flex h-full w-[480px] max-w-full flex-col bg-white shadow-[-16px_0_48px_rgba(15,15,15,0.08),_-2px_0_8px_rgba(15,15,15,0.04)]\"",
"        initial={shouldReduceMotion ? { opacity: 0 } : { opacity: 0, x: 72, scale: 0.985, filter: \"blur(2px)\" }}",
"        animate={{ opacity: 1, x: 0, scale: 1, filter: \"blur(0px)\" }}",
"        exit={shouldReduceMotion ? { opacity: 0 } : { opacity: 0, x: 48, scale: 0.99, filter: \"blur(1.5px)\" }}",
"        transition={{ duration: shouldReduceMotion ? 0.16 : 0.34, ease: springEase }}",
"        style={{ transformOrigin: \"right center\", willChange: \"transform, opacity, filter\" }}",
"      >",
"        {phase === \"processing\" && (",
"          <div className=\"absolute top-0 left-0 right-0 z-10 h-[3px] bg-[#f0efed]\">",
"            <motion.div className=\"h-full\" animate={{ width: progressPct, backgroundColor: allDone ? \"#1aae39\" : \"#0075de\" }} transition={{ duration: 0.4, ease: easeOut }} />",
"          </div>",
"        )}",
"        <AnimatePresence mode=\"wait\">",
"          {phase === \"upload\" ? (",
"            <motion.div key=\"upload\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15, ease: easeOut }} className=\"flex h-full flex-col\">",
"              <div className=\"flex items-start justify-between border-b border-[#f0efed] px-7 pt-6 pb-5\">",
"                <div>",
"                  <h2 className=\"text-[17px] font-semibold leading-6 tracking-[-0.15px] text-[#2c2c2b]\">Upload invoices</h2>",
"                  <p className=\"mt-1 text-[13px] leading-5 text-[#a39e98]\">Drop files and we&rsquo;ll extract the details automatically</p>",
"                </div>",
"                <button type=\"button\" onClick={onClose} className=\"ml-4 flex size-7 shrink-0 items-center justify-center rounded-[7px] text-[#a39e98] outline-none transition-colors duration-75 hover:bg-[#f6f5f4] hover:text-[#5f5e59]\">",
"                  <X size={15} strokeWidth={1.8} />",
"                </button>",
"              </div>",
"              <div className=\"flex-1 overflow-y-auto px-7 py-6 [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]\">",
"                <button",
"                  type=\"button\"",
"                  onClick={() => fileInputRef.current?.click()}",
"                  onDragOver={handleDragOver}",
"                  onDragLeave={handleDragLeave}",
"                  onDrop={handleDrop}",
"                  className={`group/drop flex w-full flex-col items-center rounded-[14px] border border-dashed outline-none transition-colors duration-200 ${hasFiles ? \"py-8\" : \"py-14\"} ${isDragOver ? \"border-[#0075de] bg-[#f0f7ff]\" : \"border-[#dedbd7] bg-[#fafaf9] hover:border-[#b5b0aa] hover:bg-[#f6f5f4]\"}`}",
"                >",
"                  <div className=\"relative h-[58px] w-[58px]\">",
"                    <motion.div className=\"absolute inset-1 rounded-[9px] border border-[#e6e6e6] bg-white\" animate={isDragOver ? { rotate: -11, x: -15, y: 3 } : { rotate: -7, x: -9, y: 4 }} transition={{ duration: 0.26, ease: easeOut }} />",
"                    <motion.div className=\"absolute inset-1 rounded-[9px] border border-[#e6e6e6] bg-white\" animate={isDragOver ? { rotate: 11, x: 15, y: 3 } : { rotate: 7, x: 9, y: 4 }} transition={{ duration: 0.26, ease: easeOut }} />",
"                    <motion.div className=\"absolute inset-0 flex items-center justify-center rounded-[10px] border border-[#e6e6e6] bg-white shadow-[0_1px_3px_rgba(0,0,0,0.06)]\" animate={isDragOver && !shouldReduceMotion ? { y: [-4, -8, -4], scale: 1.04 } : { y: 0, scale: 1 }} transition={isDragOver ? { duration: 0.9, repeat: Infinity, ease: \"easeInOut\" } : { duration: 0.26, ease: easeOut }}>",
"                      <FileText size={22} strokeWidth={1.6} className=\"text-[#0075de]\" />",
"                    </motion.div>",
"                    <motion.span className=\"absolute -right-2 -top-2 text-[#62aef0]\" animate={shouldReduceMotion ? { opacity: 1 } : { opacity: [0.5, 1, 0.5], scale: [0.92, 1.06, 0.92], rotate: [0, 8, 0] }} transition={{ duration: 2.2, repeat: Infinity, ease: \"easeInOut\" }}>",
"                      <Sparkles size={14} strokeWidth={1.8} />",
"                    </motion.span>",
"                  </div>",
"                  <p className={`mt-4 text-[14px] font-medium leading-5 transition-colors duration-150 ${isDragOver ? \"text-[#0075de]\" : \"text-[#31302e]\"}`}>",
"                    {isDragOver ? \"Release to add\" : hasFiles ? \"Drop more files\" : \"Drop your invoices here\"}",
"                  </p>",
"                  <p className=\"mt-1 text-[13px] leading-5 text-[#a39e98]\">",
"                    {isDragOver ? \" \" : hasFiles ? `${files.length} ${files.length === 1 ? \"file\" : \"files\"} added` : \"or click to browse — PDF, JPG, PNG up to 20 MB\"}",
"                  </p>",
"                </button>",
"                <AnimatePresence>",
"                  {hasFiles && (",
"                    <motion.div key=\"filelist\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, transition: { duration: 0.12, ease: easeOut } }} className=\"mt-4 flex flex-col gap-2\">",
"                      <AnimatePresence initial={false}>",
"                        {files.map((file, index) => {",
"                          const { ext, color, bg } = getFileExt(file);",
"                          return (",
"                            <motion.div",
"                              key={`${file.name}-${file.size}-${index}`}",
"                              layout",
"                              initial={shouldReduceMotion ? { opacity: 0 } : { opacity: 0, y: 6, scale: 0.98 }}",
"                              animate={{ opacity: 1, y: 0, scale: 1 }}",
"                              exit={{ opacity: 0, scale: 0.96 }}",
"                              transition={{ duration: 0.2, ease: easeOut }}",
"                              className=\"flex items-center gap-3 rounded-[10px] border border-[#e6e6e6] bg-white px-3 py-2.5\"",
"                            >",
"                              <span className=\"flex size-8 shrink-0 items-center justify-center rounded-[7px] text-[10px] font-bold tracking-wide\" style={{ background: bg, color }}>{ext}</span>",
"                              <span className=\"min-w-0 flex-1\">",
"                                <p className=\"truncate text-[13px] font-medium leading-5 text-[#31302e]\">{file.name}</p>",
"                                <p className=\"flex items-center gap-1 text-[11px] leading-4 text-[#a39e98]\">",
"                                  <span className=\"size-[5px] rounded-full bg-[#1aae39]\" />",
"                                  Ready &middot; {formatBytes(file.size)}",
"                                </p>",
"                              </span>",
"                              <button type=\"button\" onClick={() => removeFile(index)} className=\"flex size-6 shrink-0 items-center justify-center rounded-[6px] text-[#c9c4be] outline-none transition-colors duration-75 hover:bg-[#f6f5f4] hover:text-[#5f5e59]\">",
"                                <X size={12} strokeWidth={2} />",
"                              </button>",
"                            </motion.div>",
"                          );",
"                        })}",
"                      </AnimatePresence>",
"                    </motion.div>",
"                  )}",
"                </AnimatePresence>",
"                <div className=\"flex items-center gap-3 pb-4 pt-6\">",
"                  <div className=\"h-px flex-1 bg-[#e6e6e6]\" />",
"                  <span className=\"text-[12px] leading-4 text-[#c9c4be]\">or</span>",
"                  <div className=\"h-px flex-1 bg-[#e6e6e6]\" />",
"                </div>",
"                <div className=\"flex gap-2\">",
"                  <button type=\"button\" onClick={() => cameraInputRef.current?.click()} className=\"inline-flex h-9 flex-1 items-center justify-center gap-1.5 rounded-[8px] border border-[#e6e6e6] bg-white px-4 text-[14px] font-medium text-[#31302e] shadow-[0_1px_2px_rgba(0,0,0,0.05)] outline-none transition-colors duration-75 hover:bg-[#f6f5f4]\">",
"                    <Camera size={14} strokeWidth={1.8} aria-hidden=\"true\" className=\"text-[#8f8983]\" />",
"                    Take photo",
"                  </button>",
"                  <button type=\"button\" onClick={() => fileInputRef.current?.click()} className=\"inline-flex h-9 flex-1 items-center justify-center gap-1.5 rounded-[8px] border border-[#e6e6e6] bg-white px-4 text-[14px] font-medium text-[#31302e] shadow-[0_1px_2px_rgba(0,0,0,0.05)] outline-none transition-colors duration-75 hover:bg-[#f6f5f4]\">",
"                    <FolderOpen size={14} strokeWidth={1.8} aria-hidden=\"true\" className=\"text-[#8f8983]\" />",
"                    Choose file",
"                  </button>",
"                </div>",
"              </div>",
"              <div className=\"border-t border-[#e6e6e6] px-7 py-5\">",
"                <button type=\"button\" disabled={!hasFiles} onClick={handleUpload} className=\"inline-flex h-10 w-full items-center justify-center gap-2 rounded-[10px] bg-[#0075de] px-4 text-[14px] font-medium text-white shadow-[0_1px_2px_rgba(0,117,222,0.22),_0_0_0_1px_rgba(0,117,222,0.12)] outline-none transition-all duration-75 hover:bg-[#005bab] active:scale-[0.99] disabled:cursor-not-allowed disabled:opacity-40\">",
"                  <Sparkles size={14} strokeWidth={1.8} aria-hidden=\"true\" />",
"                  {hasFiles ? `Extract ${files.length} ${files.length === 1 ? \"invoice\" : \"invoices\"} with AI` : \"Add files to continue\"}",
"                </button>",
"              </div>",
"            </motion.div>",
"          ) : (",
"            <motion.div key=\"processing\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.2, ease: easeOut }} className=\"flex h-full flex-col pt-[3px]\">",
"              <div className=\"flex items-center justify-between border-b border-[#f0efed] px-7 pt-6 pb-5\">",
"                <div className=\"flex min-w-0 items-center gap-3\">",
"                  <AnimatePresence mode=\"wait\">",
"                    {allDone ? (",
"                      <motion.span key=\"ok\" initial={{ scale: 0.5, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: 0.22, ease: easeOut }} className=\"flex size-9 shrink-0 items-center justify-center rounded-full bg-[#e9f7ef]\">",
"                        <Check size={16} strokeWidth={2.5} className=\"text-[#1f7a4d]\" />",
"                      </motion.span>",
"                    ) : (",
"                      <motion.span key=\"spin\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className=\"flex size-9 shrink-0 items-center justify-center rounded-full bg-[#f0f7ff]\">",
"                        <span className=\"size-[17px] animate-spin rounded-full border-2 border-[#0075de]/15 border-t-[#0075de]\" />",
"                      </motion.span>",
"                    )}",
"                  </AnimatePresence>",
"                  <div className=\"min-w-0\">",
"                    <AnimatePresence mode=\"wait\">",
"                      {allDone ? (",
"                        <motion.h2 key=\"done-h\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className=\"text-[17px] font-semibold leading-6 tracking-[-0.15px] text-[#1f7a4d]\">",
"                          {files.length} {files.length === 1 ? \"invoice\" : \"invoices\"} ready",
"                        </motion.h2>",
"                      ) : (",
"                        <motion.h2 key=\"proc-h\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className=\"text-[17px] font-semibold leading-6 tracking-[-0.15px] text-[#2c2c2b]\">",
"                          Extracting invoices",
"                        </motion.h2>",
"                      )}",
"                    </AnimatePresence>",
"                    <p className=\"mt-0.5 text-[13px] leading-5 text-[#a39e98]\">",
"                      {allDone ? \"All details extracted successfully\" : `${doneCount} of ${files.length} done`}",
"                    </p>",
"                  </div>",
"                </div>",
"                <button type=\"button\" onClick={onClose} className=\"ml-4 flex size-7 shrink-0 items-center justify-center rounded-[7px] text-[#a39e98] outline-none transition-colors duration-75 hover:bg-[#f6f5f4] hover:text-[#5f5e59]\">",
"                  <X size={15} strokeWidth={1.8} />",
"                </button>",
"              </div>",
"              <div className=\"flex-1 overflow-y-auto px-7 py-2 [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]\">",
"                <div className=\"divide-y divide-[#f4f3f1]\">",
"                  {files.map((file, i) => {",
"                    const s = statuses[i] ?? 0;",
"                    const done   = s === 3;",
"                    const active = s === 1 || s === 2;",
"                    const { ext, color, bg } = getFileExt(file);",
"                    return (",
"                      <div key={i} className=\"flex items-center gap-3 py-3\">",
"                        <span className=\"flex size-8 shrink-0 items-center justify-center rounded-[7px] text-[10px] font-bold tracking-wide\" style={{ background: bg, color }}>{ext}</span>",
"                        <div className=\"min-w-0 flex-1\">",
"                          <p className={`truncate text-[13px] font-medium leading-5 transition-colors duration-200 ${done ? \"text-[#a39e98]\" : \"text-[#31302e]\"}`}>{file.name}</p>",
"                          <AnimatePresence mode=\"wait\">",
"                            {done ? (",
"                              <motion.p key=\"d\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className=\"text-[11px] font-medium leading-4 text-[#1aae39]\">Extracted</motion.p>",
"                            ) : active ? (",
"                              <motion.p key=\"a\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className=\"text-[11px] font-medium leading-4 text-[#0075de]\">{s === 1 ? \"Reading…\" : \"Analyzing…\"}</motion.p>",
"                            ) : (",
"                              <motion.p key=\"w\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className=\"text-[11px] leading-4 text-[#c9c4be]\">Waiting</motion.p>",
"                            )}",
"                          </AnimatePresence>",
"                        </div>",
"                        <div className=\"flex size-5 shrink-0 items-center justify-center\">",
"                          {done ? (",
"                            <span className=\"flex size-5 items-center justify-center rounded-full bg-[#e9f7ef]\"><Check size={9} strokeWidth={2.8} className=\"text-[#1f7a4d]\" /></span>",
"                          ) : active ? (",
"                            <span className=\"size-4 animate-spin rounded-full border-[1.5px] border-[#0075de]/20 border-t-[#0075de]\" />",
"                          ) : (",
"                            <span className=\"size-2 rounded-full bg-[#e0deda]\" />",
"                          )}",
"                        </div>",
"                        <AnimatePresence>",
"                          {done && (",
"                            <motion.button type=\"button\" initial={{ opacity: 0, x: -4 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.18, ease: easeOut }} className=\"shrink-0 text-[12px] font-medium text-[#0075de] outline-none transition-colors duration-75 hover:text-[#005bab]\">",
"                              View",
"                            </motion.button>",
"                          )}",
"                        </AnimatePresence>",
"                      </div>",
"                    );",
"                  })}",
"                </div>",
"              </div>",
"              <div className=\"border-t border-[#e6e6e6] px-7 py-5\">",
"                <AnimatePresence mode=\"wait\">",
"                  {allDone ? (",
"                    <motion.button key=\"view-all\" type=\"button\" initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.24, ease: easeOut }} className=\"inline-flex h-10 w-full items-center justify-center gap-2 rounded-[10px] bg-[#0075de] px-4 text-[14px] font-medium text-white outline-none transition-all duration-75 hover:bg-[#005bab] active:scale-[0.99]\">",
"                      <ArrowRight size={14} strokeWidth={2} aria-hidden=\"true\" />",
"                      View all invoices",
"                    </motion.button>",
"                  ) : (",
"                    <motion.div key=\"progress-label\" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className=\"flex items-center justify-center gap-2 text-[13px] text-[#a39e98]\">",
"                      <span className=\"size-[13px] animate-spin rounded-full border-[1.5px] border-[#0075de]/15 border-t-[#0075de]\" />",
"                      AI is reading your invoices…",
"                    </motion.div>",
"                  )}",
"                </AnimatePresence>",
"              </div>",
"            </motion.div>",
"          )}",
"        </AnimatePresence>",
"        <input ref={fileInputRef} type=\"file\" multiple accept=\".pdf,.jpg,.jpeg,.png\" className=\"hidden\" onChange={e => addFiles(e.target.files)} />",
"        <input ref={cameraInputRef} type=\"file\" accept=\"image/*\" capture=\"environment\" className=\"hidden\" onChange={e => addFiles(e.target.files)} />",
"      </motion.div>",
"    </div>",
"  );",
"}",
];

lines = [...lines.slice(0, startIdx), ...uploadDrawer, ...lines.slice(endIdx + 1)];

// ── 3. Fix parent state references ──
lines = lines.map(l =>
  l.replace('const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);',
            'const [isUploadDrawerOpen, setIsUploadDrawerOpen] = useState(false);')
   .replace('onClick={() => setIsCreateModalOpen(true)}',
            'onClick={() => setIsUploadDrawerOpen(true)}')
);

// ── 4. Fix AnimatePresence block ──
const joined0 = lines.join('\n');
const oldBlock = "      <AnimatePresence>\n        {isCreateModalOpen ? (\n          <CreateInvoiceModal onClose={() => setIsCreateModalOpen(false)} />\n        ) : null}\n      </AnimatePresence>";
const newBlock = "      <AnimatePresence>\n        {isUploadDrawerOpen ? (\n          <UploadDrawer key=\"upload-drawer\" onClose={() => setIsUploadDrawerOpen(false)} />\n        ) : null}\n      </AnimatePresence>";

if (!joined0.includes(oldBlock)) {
  console.error('ERROR: AnimatePresence block not found');
  // Print surroundings for debugging
  const idx = joined0.indexOf('isCreateModalOpen');
  if (idx !== -1) console.log('Context:', JSON.stringify(joined0.slice(Math.max(0, idx - 50), idx + 150)));
  process.exit(1);
}

const joined = joined0.replace(oldBlock, newBlock);
const out = crlf ? joined.replace(/\n/g, '\r\n') : joined;
fs.writeFileSync(filePath, out, 'utf8');
console.log('Done! Final lines:', joined.split('\n').length);
